name: Deploy Domain

on: [push]
# on:
#   push:
#     branches: ['*']

jobs:
  rodar-domain:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: files.000webhost.com
        username: testeilson
        password: lucia@pitoco
        server-dir: /public_html/