name: CI CONDICIONAL

on: [push]

jobs:
  teste-global:
    if: false 
    # if: ${{ false }}
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - run: echo 'FIM DO TESTE GLOBAL'

  rodar-sucesso:
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - SUCESSO'

  rodar-falhou:
    if: ${{ failure() }}
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - FALHOU'
