name: CI CONDICIONAL

on: [push]

jobs:
  teste-global:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - run: ls -la
    - run: echo 'FIM DO TESTE GLOBAL'

  rodar-sucesso:
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - SUCESSO'

  rodar-falhou:
    if: ${{ failure() }}
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - FALHOU'
