name: CI GLOBAL

on:
  push:
    branches:
      - main

jobs:
  teste-global:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - run: npm run teste
    - run: ls -la
    - run: echo 'FIM DO TESTE GLOBAL'

  rodar-sucesso:
    if: ${{ success() }}
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - SUCESSO'

  rodar-falhou:
    if: ${{ failure() }}
    #  if: ${{ job.status == 'failure' }}
    # if: ${{ github.action_status == 'failure' }}

    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - FALHOU'

  rodar-sempre:
    if: ${{ always() }}
    runs-on: ubuntu-20.04
    needs: teste-global

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE GLOBAL - SEMPRE'

  rodar-baseado:
    if: ${{ always() }}
    runs-on: ubuntu-20.04
    needs: [teste-global,rodar-sucesso]

    steps:
    - uses: actions/checkout@v2
    - run: echo 'TESTE BASEADO EM - TESTE GLOBAL + FALHOU'
    