name: 'My Workflow'

on: [push]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: UJsLSbIBqj01sg9sFiD8r_NjyV6SddiqTXIBM96WeXA
          NETLIFY_DEPLOY_TO_PROD: true