name: Deploy Surge

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: actions/setup-node@v2
        with:
          node-version: 8
      - run: npm install -g surge
      - run: surge ./ ilson1.surge.sh --token fd210f39310db922003e5f5887984052