name: CI TESTES

on: [push]

# on:
#   push:
#   pull_request:

jobs:
  test-ci:
    # if: false 
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        # node-version: [14.x, 16.x]
        node-version: [8.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run test
    - run: echo 'FIM DOS TESTES'